pipeline {
    agent any
    stages {
        
        stage('Staging'){
            steps{
                echo 'Starting staging job'
                build job: 'PIPELINE-FULL-STAGING', parameters: [
                      string(name:'ENVIRONMENT', value: "staging")]
            }
        }
        stage('Merge'){
            steps{
                sh script: """
                    set -x
                    git branch -a
                    git checkout -b develop origin/develop
                    git checkout -b master origin/master
                    git merge develop
                """, label: "Merging code to master"
                hub remote set-url upstream https://$token:x-oauth-basic@github.com/$owner/$repo.git
                hub remote set-url origin https://$token:x-oauth-basic@github.com/$username/$repo.git
                sh 'git push origin master'
            }
        }
        stage('Production'){
            steps{
                
                echo 'Starting production job'
                build job: 'PIPELINE-FULL-PRODUCTION', parameters: [
                      string(name:'ENVIRONMENT', value: "production")]
            }
        }
    }
    post { 
        always { 
            echo 'Clean env: delete dir'
            cleanWs()
        }
    }
}